{
  description = "Docker container with SSH server and Nix using canonical NixOS configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system: let
      # Use host system for building tools and scripts
      pkgs = nixpkgs.legacyPackages.${system};
      
      # Always build Docker image for aarch64-linux to match Colima target
      targetSystem = "aarch64-linux";
      targetPkgs = nixpkgs.legacyPackages.${targetSystem};
      
      # Use NixOS module evaluation to generate SSH configuration
      # This is the canonical way to use services.openssh in NixOS
      sshModule = nixpkgs.lib.evalModules {
        modules = [
          # Import the openssh NixOS module
          "${nixpkgs}/nixos/modules/services/networking/ssh/sshd.nix"
          # Import required base modules
          "${nixpkgs}/nixos/modules/misc/ids.nix"
          "${nixpkgs}/nixos/modules/config/users-groups.nix"
          
          # Our SSH configuration using canonical services.openssh
          ({ config, lib, pkgs, ... }: {
            # Use the canonical NixOS services.openssh configuration
            services.openssh = {
              enable = true;
              settings = {
                PermitRootLogin = "yes";
                PubkeyAuthentication = true;
                PasswordAuthentication = false;
                UsePAM = false;
                StrictModes = true;
                X11Forwarding = false;
                PrintMotd = false;
                LogLevel = "INFO";
                MaxAuthTries = 6;
                MaxSessions = 10;
              };
              hostKeys = [
                { path = "/etc/ssh/ssh_host_ed25519_key"; type = "ed25519"; }
                { path = "/etc/ssh/ssh_host_rsa_key"; type = "rsa"; bits = 4096; }
                { path = "/etc/ssh/ssh_host_ecdsa_key"; type = "ecdsa"; bits = 521; }
              ];
            };
            
            # Required for module evaluation
            system.stateVersion = "23.11";
            nixpkgs.system = targetSystem;
          })
        ];
        
        specialArgs = { 
          pkgs = targetPkgs; 
        };
      };
      
      # Extract the SSH configuration generated by the canonical NixOS services.openssh module
      sshdConfigFile = pkgs.writeTextFile {
        name = "sshd_config";
        text = sshModule.config.environment.etc."ssh/sshd_config".text;
        destination = "/etc/ssh/sshd_config";
      };
      
      # Extract the SSH host key configuration
      sshHostKeys = sshModule.config.services.openssh.hostKeys;
      
      # Create essential system files that Docker needs to find the root user
      passwdFile = pkgs.writeTextFile {
        name = "passwd";
        text = ''
          root:x:0:0:root:/root:${targetPkgs.bash}/bin/bash
          sshd:x:74:74:SSH daemon:/var/empty:/bin/false
        '';
        destination = "/etc/passwd";
      };
      
      groupFile = pkgs.writeTextFile {
        name = "group";
        text = ''
          root:x:0:
          sshd:x:74:
        '';
        destination = "/etc/group";
      };
      
      shadowFile = pkgs.writeTextFile {
        name = "shadow";
        text = ''
          root:!:19000:0:99999:7:::
          sshd:!:19000:0:99999:7:::
        '';
        destination = "/etc/shadow";
      };
      
      # Nix configuration
      nixConfig = pkgs.writeTextFile {
        name = "nix.conf";
        text = ''
          experimental-features = nix-command flakes
          trusted-users = root
          sandbox = false
          substituters = https://cache.nixos.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
        '';
        destination = "/root/.config/nix/nix.conf";
      };
      
      # Entrypoint script that uses the canonical NixOS-generated SSH configuration  
      entrypoint = pkgs.writeTextFile {
        name = "entrypoint";
        text = ''
#!${targetPkgs.bash}/bin/bash
set -euo pipefail

echo "Starting SSH server with canonical NixOS services.openssh configuration..."

# Create required directories
mkdir -p /etc/ssh /var/run/sshd /var/empty /root/.ssh

# Set proper permissions on shadow file
chmod 640 /etc/shadow

# Generate SSH host keys using the canonical NixOS services.openssh specification
echo "Generating SSH host keys using NixOS services.openssh specification..."
${builtins.concatStringsSep "\n" (map (key: 
  let 
    keyPath = key.path; 
    keyType = key.type; 
    keyBits = toString (key.bits or ""); 
  in
  ''
    if [ ! -f ${keyPath} ]; then
      echo "Generating ${keyType} host key at ${keyPath}..."
      ${targetPkgs.openssh}/bin/ssh-keygen -t ${keyType} ${if keyBits != "" then "-b ${keyBits}" else ""} -f ${keyPath} -N "" -q
      chmod 600 ${keyPath}
      chmod 644 ${keyPath}.pub
    fi
  ''
) sshHostKeys)}

# Set proper permissions on SSH directories
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys 2>/dev/null || true

# Test SSH configuration using NixOS-generated config
echo "Testing canonical NixOS services.openssh configuration..."
${targetPkgs.openssh}/bin/sshd -T -f /etc/ssh/sshd_config

# Start SSH daemon with canonical NixOS services.openssh configuration
echo "SSH server ready, starting daemon with canonical NixOS services.openssh configuration..."
exec ${targetPkgs.openssh}/bin/sshd -D -f /etc/ssh/sshd_config
        '';
        executable = true;
        destination = "/bin/entrypoint";
      };
    in {
      packages = {
        # Docker image with SSH and Nix configured using canonical NixOS services.openssh approach
        nix-remote-builder = pkgs.dockerTools.buildImage {
          name = "nix-remote-builder";
          tag = "latest";
          
          # Copy packages and system files to root filesystem
          copyToRoot = pkgs.buildEnv {
            name = "image-root";
            paths = with targetPkgs; [
              bash
              coreutils
              gnugrep  
              procps   
              nettools 
              netcat   
              openssh
              nix
              git
              gnutar
              gzip
              xz
            ] ++ [
              # System files and SSH config generated by NixOS services.openssh
              entrypoint
              passwdFile
              groupFile
              shadowFile
              nixConfig
              sshdConfigFile  # Generated by canonical NixOS services.openssh module
            ];
          };
          
          # Configuration for the image
          config = {
            Env = [
              "PATH=/bin:/usr/bin:/nix/var/nix/profiles/default/bin"
              "USER=root"
              "HOME=/root"
            ];
            
            ExposedPorts = {
              "22/tcp" = {};
            };
            
            WorkingDir = "/root";
            User = "root";
            Cmd = [ "/bin/entrypoint" ];
          };
        };
        default = self.packages.${system}.nix-remote-builder;
      };
      
      # Development shell for building the image
      devShells.default = pkgs.mkShell {
        packages = with pkgs; [
          docker
          nix
        ];
        
        shellHook = ''
          echo "🐳 Docker container builder with canonical NixOS SSH configuration"
          echo "Available commands:"
          echo "  nix build .#nix-remote-builder  - Build the Docker container"
          echo "  docker load < result             - Load the container into Docker"
          echo ""
          echo "This container uses the canonical NixOS services.openssh module"
          echo "to generate SSH configuration, host keys, and daemon settings."
        '';
      };
    });
}